/**
 * 아첼 청소년 오케스트라 및 한국가톨릭문화원 실제 데이터
 */

import type {
  Concert,
  Member,
  Group,
  ConcertMember,
  Repertoire,
  ProgramItem,
} from '../types';

// ============================================================
// 아첼 청소년 오케스트라 데이터
// ============================================================

export const AZEL_GROUP: Group = {
  id: 'group-azel',
  name: '아첼 청소년 오케스트라',
  type: '오케스트라',
  representative: '심우림',
  phone: '010-xxxx-xxxx',
  status: '운영중',
  createdAt: new Date().toISOString(),
};

export const AZEL_CONCERTS: Concert[] = [
  {
    id: 'az24',
    groupId: 'group-azel',
    title: '제24회 아첼 청소년 오케스트라 정기연주회',
    date: '2015-03-28',
    time: '15:00',
    place: '고양 별모래 어린이극장',
    conductor: '김도현',
    status: '완료',
    expectedDuration: 90,
    progressRate: 100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'az26',
    groupId: 'group-azel',
    title: '제26회 아첼 청소년 오케스트라 정기연주회',
    date: '2016-03-19',
    time: '15:00',
    place: '고양 별모래 어린이극장',
    conductor: '김도현',
    status: '완료',
    expectedDuration: 90,
    progressRate: 100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'az28',
    groupId: 'group-azel',
    title: '제28회 아첼 청소년 오케스트라 정기연주회',
    date: '2017-03-18',
    time: '15:00',
    place: '고양 별모래 어린이극장',
    conductor: '김도현',
    status: '완료',
    expectedDuration: 90,
    progressRate: 100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'az30',
    groupId: 'group-azel',
    title: '제30회 아첼 청소년 오케스트라 정기연주회',
    date: '2018-03-24',
    time: '15:00',
    place: '고양 별모래 어린이극장',
    conductor: '김도현',
    status: '완료',
    expectedDuration: 90,
    progressRate: 100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'az32',
    groupId: 'group-azel',
    title: '제32회 아첼 청소년 오케스트라 정기연주회',
    date: '2018-12-24',
    time: '15:00',
    place: '고양 별모래 어린이극장',
    conductor: '김도현',
    status: '완료',
    expectedDuration: 90,
    progressRate: 100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'az35',
    groupId: 'group-azel',
    title: '제35회 아첼 청소년 오케스트라 정기연주회',
    date: '2020-11-07',
    time: '15:00',
    place: '고양 별모래 어린이극장',
    conductor: '김도현',
    status: '완료',
    expectedDuration: 90,
    progressRate: 100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'az37',
    groupId: 'group-azel',
    title: '제37회 아첼 청소년 오케스트라 정기연주회',
    date: '2022-06-12',
    time: '15:00',
    place: '고양 별모래 어린이극장',
    conductor: '김도현',
    status: '완료',
    expectedDuration: 90,
    progressRate: 100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'az38',
    groupId: 'group-azel',
    title: '제38회 아첼 청소년 오케스트라 정기연주회',
    date: '2022-10-30',
    time: '15:00',
    place: '고양 어울림누리',
    conductor: '김도현',
    status: '완료',
    expectedDuration: 90,
    progressRate: 100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'az39',
    groupId: 'group-azel',
    title: '제39회 아첼 청소년 오케스트라 정기연주회',
    date: '2023-03-25',
    time: '15:00',
    place: '고양 별모래 어린이극장',
    conductor: '김도현',
    status: '완료',
    expectedDuration: 90,
    progressRate: 100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'az40',
    groupId: 'group-azel',
    title: '제40회 아첼 청소년 오케스트라 정기연주회',
    date: '2023-08-20',
    time: '15:00',
    place: '고양 어울림누리',
    conductor: '김도현',
    status: '완료',
    expectedDuration: 90,
    progressRate: 100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'az41',
    groupId: 'group-azel',
    title: '제41회 아첼 청소년 오케스트라 정기연주회',
    date: '2024-03-24',
    time: '15:00',
    place: '고양 별모래 어린이극장',
    conductor: '김도현',
    status: '완료',
    expectedDuration: 90,
    progressRate: 100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'az42',
    groupId: 'group-azel',
    title: '제42회 아첼 청소년 오케스트라 정기연주회',
    date: '2024-08-10',
    time: '15:00',
    place: '고양 어울림누리',
    conductor: '김도현',
    status: '완료',
    expectedDuration: 90,
    progressRate: 100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'az43',
    groupId: 'group-azel',
    title: '제43회 아첼 청소년 오케스트라 정기연주회',
    date: '2025-03-23',
    time: '15:00',
    place: '고양 별모래 어린이극장',
    conductor: '김도현',
    status: '완료',
    expectedDuration: 90,
    progressRate: 100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'az44',
    groupId: 'group-azel',
    title: '제44회 아첼 청소년 오케스트라 정기연주회',
    date: '2025-08-09',
    time: '15:00',
    place: '고양 어울림누리',
    conductor: '김도현',
    status: '완료',
    expectedDuration: 90,
    progressRate: 100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'az45',
    groupId: 'group-azel',
    title: '제45회 아첼 청소년 오케스트라 정기연주회',
    date: '2025-12-14',
    time: '15:00',
    place: '고양 별모래 어린이극장',
    conductor: '김도현',
    status: '완료',
    expectedDuration: 90,
    progressRate: 100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'az46',
    groupId: 'group-azel',
    title: '제46회 아첼 청소년 오케스트라 정기연주회',
    date: '2026-08-01',
    time: '15:00',
    place: '고양 어울림누리',
    conductor: '김도현',
    status: '기획중',
    expectedDuration: 90,
    progressRate: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const AZEL_MEMBERS: Member[] = [
  { id: 'am1', name: '김단비', instrument: '바이올린', part: 'Violin 1', role: '바흐 2vn', phone: '', grade: 'B', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'am2', name: '장준영', instrument: '바이올린', part: 'Violin 1', role: '바흐 가보트', phone: '', grade: 'B', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'am3', name: '김연우', instrument: '바이올린', part: 'Violin 2', role: '새내기', phone: '', grade: 'B', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'am4', name: '이혜원', instrument: '바이올린', part: 'Violin 1', role: '사냥꾼', phone: '', grade: 'B', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'am5', name: '김민채', instrument: '비올라', part: 'Viola', role: '마르티니', phone: '', grade: 'B', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'am6', name: '양하준', instrument: '바이올린', part: 'Violin 1', role: '바흐 2vn', phone: '', grade: 'B', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'am7', name: '박민혁', instrument: '첼로', part: 'Cello', role: '새내기', phone: '', grade: 'B', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'am8', name: '박서연', instrument: '비올라', part: 'Viola', role: '바흐 가보트', phone: '', grade: 'B', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'am9', name: '김민희', instrument: '바이올린', part: 'Violin 1', role: '자이츠', phone: '', grade: 'B', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'am10', name: '배자인', instrument: '바이올린', part: 'Violin 1', role: '자이츠', phone: '', grade: 'B', status: '활동중', createdAt: new Date().toISOString() },
];

// ============================================================
// 한국가톨릭문화원 데이터 (기본 정보)
// ============================================================

export const CATHOLIC_GROUP: Group = {
  id: 'group-catholic',
  name: '한국가톨릭문화원 심포니 오케스트라',
  type: '오케스트라',
  representative: '',
  phone: '',
  status: '운영중',
  createdAt: new Date().toISOString(),
};

export const CATHOLIC_CONCERTS: Concert[] = [
  {
    id: 'kc57',
    groupId: 'group-catholic',
    title: '제57회 한국가톨릭문화원 심포니 오케스트라 정기연주회',
    date: '2025-12-20',
    time: '19:00',
    place: '',
    conductor: '',
    status: '완료',
    expectedDuration: 120,
    progressRate: 100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'kc58',
    groupId: 'group-catholic',
    title: '제58회 가톨릭문화원 챔버오케스트라 정기연주회',
    date: '2026-04-19',
    time: '15:00',
    place: '',
    conductor: '',
    status: '기획중',
    expectedDuration: 90,
    progressRate: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const CATHOLIC_MEMBERS: Member[] = [
  { id: 'km1', name: 'Urrecho Zubillaga, Unai', instrument: '지휘', part: '지휘', role: '', phone: '', grade: 'A', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km2', name: '이석준', instrument: '호른', part: '협연자(Horn)', role: '협연자', phone: '', grade: 'A', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km3', name: '이보연', instrument: '바이올린', part: '악장', role: '악장', phone: '', grade: 'A', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km4', name: '오병철', instrument: '플루트', part: 'Flute 1', role: '', phone: '', grade: '1', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km5', name: '문정은', instrument: '플루트', part: 'Flute 2', role: '', phone: '', grade: '2', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km6', name: '김채원', instrument: '플루트', part: 'Flute 3(Piccolo)', role: '', phone: '', grade: '3', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km7', name: '윤수연', instrument: '오보에', part: 'Oboe 1', role: '', phone: '', grade: '4', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km8', name: '박채영', instrument: '오보에', part: 'Oboe 2(E.Horn)', role: '', phone: '', grade: '5', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km9', name: '박수진', instrument: '클라리넷', part: 'Clarinet 1', role: '', phone: '', grade: '6', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km10', name: '양청하', instrument: '클라리넷', part: 'Clarinet 2(Bass)', role: '', phone: '', grade: '7', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km11', name: '탁빛나 ', instrument: '클라리넷', part: 'Clarinet 3', role: '', phone: '', grade: '8', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km12', name: '최윤호', instrument: '베이스', part: 'Basson 1', role: '', phone: '', grade: '9', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km13', name: '지인석', instrument: '베이스', part: 'Basson 2', role: '', phone: '', grade: '10', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km14', name: '홍대범', instrument: '트럼펫', part: 'Trumpet 1', role: '', phone: '', grade: '1', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km15', name: '양지원', instrument: '트럼펫', part: 'Trumpet 2', role: '', phone: '', grade: '2', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km16', name: '황재빈', instrument: '호른', part: 'Horn 1', role: '', phone: '', grade: '3', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km17', name: '김윤정', instrument: '호른', part: 'Horn 2', role: '', phone: '', grade: '4', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km18', name: '김진우', instrument: '호른', part: 'Horn 3', role: '', phone: '', grade: '5', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km19', name: '태한용', instrument: '호른', part: 'Horn 4', role: '', phone: '', grade: '6', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km20', name: '김종윤', instrument: '트롬본', part: 'Trombone 1', role: '', phone: '', grade: '7', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km21', name: '기수인', instrument: '트롬본', part: 'Trombone 2', role: '', phone: '', grade: '8', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km22', name: '박종연', instrument: '트롬본', part: 'Trombone 3(Bass)', role: '', phone: '', grade: '9', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km23', name: '서영찬', instrument: '튜바', part: 'Tuba', role: '', phone: '', grade: '10', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km24', name: '박대순', instrument: '팀파니', part: 'Timpani', role: '', phone: '', grade: '1', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km25', name: '김호연', instrument: 'Percussion', part: 'Percussion 1', role: '', phone: '', grade: '2', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km26', name: '권태빈', instrument: 'Percussion', part: 'Percussion 2', role: '', phone: '', grade: '3', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km27', name: '김미양', instrument: 'Keyboard', part: 'Keyboard', role: '', phone: '', grade: '4', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km28', name: '유은영', instrument: '바이올린', part: '바이올린', role: '수석', phone: '', grade: '1', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km29', name: '이영재', instrument: '바이올린', part: '바이올린', role: '', phone: '', grade: '2', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km30', name: '정윤진', instrument: '바이올린', part: '바이올린', role: '', phone: '', grade: '3', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km31', name: 'Jimmy', instrument: '바이올린', part: '바이올린', role: '', phone: '', grade: '4', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km32', name: '김예슬', instrument: '바이올린', part: '바이올린', role: '', phone: '', grade: '5', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km33', name: '김혜진', instrument: '바이올린', part: '바이올린', role: '', phone: '', grade: '6', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km34', name: '강지훈', instrument: '바이올린', part: '바이올린', role: '', phone: '', grade: '7', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km35', name: '유연주', instrument: '바이올린', part: '바이올린', role: '', phone: '', grade: '8', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km36', name: '권시은', instrument: '바이올린', part: '바이올린', role: '', phone: '', grade: '9', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km37', name: '김미나', instrument: '비올라', part: '비올라', role: '수석', phone: '', grade: '1', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km38', name: '이시연', instrument: '비올라', part: '비올라', role: '', phone: '', grade: '2', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km39', name: '고영덕', instrument: '비올라', part: '비올라', role: '', phone: '', grade: '3', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km40', name: '안용희', instrument: '비올라', part: '비올라', role: '', phone: '', grade: '4', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km41', name: '홍영미', instrument: '비올라', part: '비올라', role: '', phone: '', grade: '5', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km42', name: '심진아', instrument: '비올라', part: '비올라', role: '', phone: '', grade: '6', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km43', name: '정은지', instrument: '비올라', part: '비올라', role: '', phone: '', grade: '7', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km44', name: '이승준', instrument: '비올라', part: '비올라', role: '', phone: '', grade: '8', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km45', name: '구정회', instrument: '첼로', part: '첼로', role: '수석', phone: '', grade: '1', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km46', name: '이준호', instrument: '첼로', part: '첼로', role: '', phone: '', grade: '2', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km47', name: '박성봉 ', instrument: '첼로', part: '첼로', role: '', phone: '', grade: '3', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km48', name: '남정은', instrument: '첼로', part: '첼로', role: '', phone: '', grade: '4', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km49', name: '윤태영 ', instrument: '첼로', part: '첼로', role: '', phone: '', grade: '5', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km50', name: '양인영', instrument: '첼로', part: '첼로', role: '', phone: '', grade: '6', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km51', name: '정희경', instrument: '베이스', part: '베이스', role: '수석', phone: '', grade: '1', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km52', name: '서정원', instrument: '베이스', part: '베이스', role: '', phone: '', grade: '2', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km53', name: '이영우', instrument: '베이스', part: '베이스', role: '', phone: '', grade: '3', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km54', name: '김복경', instrument: '베이스', part: '베이스', role: '', phone: '', grade: '4', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km55', name: '이지윤', instrument: '베이스', part: '베이스', role: '', phone: '', grade: '5', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km56', name: '이웅', instrument: '베이스', part: '베이스', role: '', phone: '', grade: '6', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km57', name: '박준건', instrument: '바이올린', part: '바이올린', role: '수석', phone: '', grade: '1', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km58', name: '신광윤', instrument: '악기', part: '', role: '', phone: '', grade: '2', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km59', name: '박유림', instrument: '악기', part: '', role: '', phone: '', grade: '3', status: '활동중', createdAt: new Date().toISOString() },
  { id: 'km60', name: '이가람', instrument: '악기', part: '', role: '', phone: '', grade: '4', status: '활동중', createdAt: new Date().toISOString() },
];
